### ISSUE TITLE
Type Cast not matching on eager_load

### ISSUE THREAD

**Issue by pablotarga** [alekseyl/rails_select_on_includes#3]
Not sure if it is related to this gem or it's rails fault. I'm getting different results when I use eager_load

String, Fixnum and Booleans are ok:
```ruby
Post.eager_load(:comments).select("posts.*, 1 as testval").first.testval.class
# Fixnum
Post.eager_load(:comments).select("posts.*, 'test' as testval").first.testval.class
# String
Post.eager_load(:comments).select("posts.*, true as testval").first.testval.class
# TrueClass
```

But on other types are converted to String:
```ruby
Post.select("posts.*, .1 as testval").first.testval.class
# BigDecimal
Post.eager_load(:comments).select("posts.*, .1 as testval").first.testval.class
# String

Post.select("posts.*, ARRAY['Ruby'] as testval").first.testval.class
# Array
Post.eager_load(:comments).select("posts.*, ARRAY['Ruby'] as testval").first.testval.class
# String

Post.select("posts.*, '2017-02-07 12:00:00'::timestamp as testval").first.testval.class
# Time
Post.eager_load(:comments).select("posts.*, '2017-02-07 12:00:00'::timestamp as testval").first.testval.class
# String
```

Any thoughts on what is causing this?

**Comment by alekseyl** [comment]
rails version? I'll look for it.

**Comment by pablotarga** [comment]
gem 'rails', '5.0.0'

**Comment by alekseyl** [comment]
Done in 0.4.8 version 
and 0.5.2 

monkey patch is stronger now ))

**Comment by pablotarga** [comment]
Thanks a lot for caring about this issue.

I've tried the version 0.5.2 but I've got the following when triggering the query with eager_load:
```
ArgumentError: wrong number of arguments (given 3, expected 2)
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/associations/join_dependency/join_part.rb:65:in `instantiate'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/rails_select_on_includes-0.5.2/lib/rails_select_on_includes.rb:93:in `block (2 levels) in instantiate'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/result.rb:52:in `block in each'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/result.rb:52:in `each'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/result.rb:52:in `each'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/rails_select_on_includes-0.5.2/lib/rails_select_on_includes.rb:89:in `block in instantiate'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/rails_select_on_includes-0.5.2/lib/rails_select_on_includes.rb:88:in `instantiate'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/rails_select_on_includes-0.5.2/lib/rails_select_on_includes.rb:135:in `find_with_associations'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/relation.rb:699:in `exec_queries'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/relation.rb:580:in `load'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/relation.rb:260:in `records'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/relation.rb:256:in `to_a'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/relation/finder_methods.rb:561:in `find_nth_with_limit'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/relation/finder_methods.rb:590:in `find_nth_with_limit_and_offset'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activerecord-5.0.0/lib/active_record/relation/finder_methods.rb:543:in `find_nth'
... 3 levels...
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
  from /home/vagrant/projects/api/bin/rails:9:in `<top (required)>'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
  from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from -e:1:in `<main>'
```

and when with version 0.5.3. I`ve got the following when booting up the app:
```
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'rails_select_on_includes'.
Gem Load Error is: uninitialized constant ActiveRecord::Associations::JoinDependency::JoinPart
Did you mean?  ActiveRecord::Associations::JoinDependency::JoinBase
Backtrace for gem load error is:
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/rails_select_on_includes-0.5.3/lib/rails_select_on_includes.rb:59:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/home/vagrant/projects/api/config/application.rb:15:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
/home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
  from /home/vagrant/projects/api/config/application.rb:15:in `<top (required)>'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
  from /home/vagrant/.rvm/gems/ruby-2.3.1@mustard-api/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
  from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from -e:1:in `<main>'
```

**Comment by alekseyl** [comment]
try 0.5.4 pls

**Comment by pablotarga** [comment]
It worked here thanks a mil
